[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spite"
version = "0.1.1"
description = "Scattering Parameter Inspection Tool for Engineers"
readme = "README.md"
license = "0BSD"
authors = [{name = "Anthony Jeongseok Lee"}]
requires-python = ">=3.10"
dependencies = ["numpy", "matplotlib"]

